name: version_check
description: Check iOS/Android/Mac store version and provide update alert if update is available.
version: 0.3.0
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/version_check

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info: any 
  http: any
  html: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
